# Use node for running the React app
FROM node:20-alpine AS runner

WORKDIR /app

# Copy package.json and package-lock.json first
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --frozen-lockfile

# Copy the rest of the app
COPY . .

# Set environment to production
ENV NODE_ENV=production

# Start the React app using the production environment
CMD ["npm", "run", "start:production"]
